[theme]
primaryColor = "#0068c9"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730"
font = "sans serif"

[server]
runOnSave = true

[browser]
gatherUsageStats = false

[ui]
hideTopBar = false

[pages]
# Keep the page names in the navigation
hideSidebarNav = false